# Jméno dané akce na githubu
name: Build And Upload Docker Image
# Kdy se má akce spustit (při pushnutí nového commitu)
on: [push]
# Joby co má dělat blablal
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN}}
        
    - id: string
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}

    - name: Build the ${{ github.repository }} Docker image
      run: |
        docker build . --tag ghcr.io/${{ steps.string.outputs.lowercase }}:latest
        docker push ghcr.io/${{ steps.string.outputs.lowercase }}:latest
