# Jméno dané akce na githubu
name: publish
# Kdy se má akce spustit (při pushnutí nového commitu)
on: [push]
# Joby co má dělat
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN}}

    - name: Build the ${{ github.repository }} Docker image
      run: |
        docker build . --tag ghcr.io/${{ github.repository }}:latest
        docker run ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:latest
